# Generated by Django 4.1.3 on 2022-11-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='The name of the product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='The price of the product')),
                ('description', models.TextField(verbose_name='A text description for the item.')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='The height of the product.')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='The width of the product.')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='The length of the product.')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='What the user uses to login')),
                ('name', models.CharField(max_length=100, verbose_name='What the user chooses to go by')),
                ('email', models.EmailField(max_length=254, verbose_name="The user's email for order confirmations.")),
                ('joined', models.DateField(auto_now_add=True, verbose_name='Date the user joined')),
            ],
        ),
    ]
