# Generated by Django 4.1.3 on 2022-11-10 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='submitted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date the product was added'),
            preserve_default=False,
        ),
    ]
