# Generated by Django 4.1.3 on 2022-11-10 18:53

from django.db import migrations
import random

def product_data(apps, schema_editor):
	# sample names for 10 products, the data will be random and just for example
	names = ["Hanging Nutcracker Decoration", "Pack of 4 Rose Gold Blush Baubles", "Pack of 4 Red & White Baubles", "Starry Night Lantern", "Red Robin Decoration", "Light Up Bow Decoration", "Santa Hat Garland", "Candy Canes", "Silver Glass Hanging Baubles", "Santa Hat Tree Topper"]

	Product = apps.get_model("products", "Product") # get the Product model
	sample_products = [] # list for the Product sample data, so all can be added at once
	lorem = Lipsum()
	for i in range(10):
		new_product = Product(
			name=names[i],
			price=random.uniform(1, 20),
			description=next(lorem),
			height=random.uniform(1, 5),
			width=random.uniform(1, 5),
			length=random.uniform(1, 5))
		sample_products.append(new_product)
	Product.objects.bulk_create(sample_products) # add the products to the model

	

def user_data(apps, schema_editor):
	# sample data for 10 users
	names = ["Gareth Dukes", "Celestine Addison", "Mack Lamb", "Avery Ellison", "Adele Kitchens", "Kerri Simpkin", "Millard Danell", "Daisy Simpkin", "Blaine Warrick", "Kyra Herriot"]
	usernames = ["DearBedroom", "AnyResist", "InfantileGod", "BarbarousBorder", "EqualVideo", "GentleAccident", "FirsthandReflection", "CornyPopulation", "GrumpyProfit", "HolisticAmbition"]

	User = apps.get_model("products", "User") # get the User model
	sample_users = [] # list for the User sample data, so all can be added at once
	for i in range(10):
		# creating a user with one of each of the sample data
		new_user = User(
			username=usernames[i],
			name=names[i],
			email=f"{names[i][0].lower()}{names[i].split()[1]}@example.com")
		sample_users.append(new_user)
	User.objects.bulk_create(sample_users) # add the users to the model


class Migration(migrations.Migration):

	dependencies = [
		('products', '0002_product_submitted'),
	]

	operations = [
		migrations.RunPython(user_data),
		migrations.RunPython(product_data),
	]

class Lipsum:
	"""class to make a generator for lorem ipsum text"""

	def __init__(self):
		self.n = 0
		self.data = [
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam efficitur nulla sit amet tempor fringilla. Maecenas lorem nisl, vehicula in metus quis, pharetra sollicitudin felis. Vestibulum sodales erat a orci placerat, non tincidunt tortor ullamcorper. Duis mattis eleifend arcu sed bibendum. Phasellus malesuada fermentum diam, ac hendrerit ligula lacinia nec. Phasellus posuere aliquam interdum. Sed sit amet venenatis nulla. Praesent ac arcu pharetra, hendrerit nisi quis, maximus erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse iaculis molestie vehicula. Fusce varius turpis vel egestas ornare. Cras auctor felis dignissim, ultrices arcu eu, consequat felis. Suspendisse vel turpis a turpis rhoncus ultricies. Vestibulum finibus vel ligula vel tempus. Aliquam erat volutpat.",
			"Nulla quis tempor nisi. Fusce feugiat justo purus, sit amet auctor dolor sagittis a. Sed in ex at dui consectetur accumsan. Maecenas lacinia, urna at luctus rutrum, magna mi imperdiet lectus, nec lacinia felis sapien id erat. Mauris at diam ac purus gravida fringilla. Maecenas quis arcu nibh. Vivamus bibendum mauris quis lacus dignissim, in ornare lectus vulputate. Nunc urna quam, bibendum id felis sed, rutrum commodo quam. Donec sapien quam, sagittis sit amet odio eget, fermentum vulputate arcu. Donec eu nisl vel nibh suscipit suscipit nec et lorem. Proin sapien elit, fermentum luctus lorem sed, fringilla porta sem.",
			"Donec magna lacus, ornare vitae dolor at, finibus efficitur sem. Nullam vel enim aliquet, euismod tortor vitae, dignissim nunc. Ut sed diam consectetur augue consectetur bibendum. Donec in tortor non dui ornare sodales ut sed leo. Suspendisse faucibus ligula porttitor turpis condimentum, ac iaculis lectus dictum. Proin id euismod elit, hendrerit blandit tortor. Phasellus semper neque eros, ut porttitor nibh feugiat ac. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc sagittis in erat iaculis aliquam. Aenean eget risus odio. Nullam tempor tellus dolor, vitae mattis leo laoreet non. Duis euismod elementum auctor. Duis nunc erat, posuere id bibendum vitae, cursus quis lorem. Nam tortor magna, consectetur in felis vel, maximus eleifend nulla.",
			"Maecenas vestibulum faucibus euismod. Praesent eleifend purus turpis, ac finibus lorem vestibulum a. Aliquam risus dui, tempor maximus pharetra vel, pulvinar a sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer venenatis non metus vel aliquam. Nam vitae nulla dapibus enim egestas sollicitudin vitae sit amet justo. Pellentesque ut lorem ex. Praesent malesuada convallis turpis, at posuere magna tempor iaculis. Proin maximus malesuada nisl at mattis. Ut urna ante, euismod non suscipit vestibulum, posuere nec orci.",
			"Fusce convallis, sem nec varius placerat, nisl mi sagittis arcu, eu cursus urna purus sit amet justo. Praesent tincidunt pretium neque id posuere. In vestibulum congue orci eu gravida. Pellentesque laoreet feugiat sapien, maximus sodales urna vulputate id. Fusce suscipit nunc ut dui eleifend vestibulum. Mauris venenatis faucibus nulla a euismod. Sed ullamcorper et dui nec aliquam. Nulla hendrerit congue libero in vulputate.",
			"Aliquam erat volutpat. Donec fermentum tortor risus, ultricies convallis arcu condimentum eu. Vivamus bibendum eu turpis vitae egestas. Praesent dapibus urna id sapien placerat, a mollis dolor scelerisque. Ut maximus non ligula vitae bibendum. Sed a arcu sit amet massa viverra mollis. Mauris nec pulvinar quam, quis tempor mauris. Nam elementum auctor tincidunt. Sed tincidunt, orci eget facilisis pulvinar, sem turpis vehicula mi, quis ornare mauris nulla ac nisl. Nulla facilisi. Nulla at augue at lorem consectetur molestie eget vitae nunc. Proin lobortis ante et laoreet scelerisque. Pellentesque nec leo quis nulla porta porta ut ut ante. Pellentesque eget egestas magna, commodo dictum dui. Nulla vitae ultricies magna.",
			"Suspendisse aliquet, purus eu vehicula convallis, nulla felis cursus sem, ac venenatis dui lorem a leo. Donec consequat libero leo, at rutrum tellus consequat eu. Nullam elementum, lorem nec auctor vehicula, est ligula cursus ante, id lobortis tortor orci a lectus. Quisque scelerisque, dui quis tempor lacinia, ex arcu rhoncus magna, cursus commodo elit urna vel risus. Vivamus auctor libero id odio aliquam lobortis. Nullam at ligula arcu. Proin et sollicitudin dolor, bibendum euismod elit. Maecenas a fermentum quam. Duis sollicitudin quam nec mi fermentum, eget consectetur nisi sodales. Phasellus porttitor cursus neque at tristique. Nam nec ante non massa interdum laoreet at quis erat. Praesent tristique, odio eu rutrum volutpat, mi ligula dictum neque, scelerisque auctor ligula quam non tellus.",
			"Donec lacinia metus ac ante accumsan aliquet. Pellentesque tristique ipsum a gravida tempus. Nunc porta sem a sagittis tincidunt. Morbi id mi et leo scelerisque porta. Integer ac pretium orci, eget posuere metus. Suspendisse aliquam cursus dui, at maximus ex tincidunt et. Phasellus convallis sodales arcu ac posuere. Vivamus fringilla mauris quis urna tincidunt mollis. Vestibulum vehicula, sapien sit amet imperdiet dapibus, enim tellus auctor urna, quis pulvinar massa metus lacinia diam. Suspendisse vel ipsum mattis libero rutrum sollicitudin. Etiam dapibus, nisl ac faucibus malesuada, lectus ex vestibulum dui, et faucibus nibh odio quis lacus. Proin cursus dapibus mi, et vulputate elit convallis tincidunt. Nulla molestie quis ex et laoreet. Praesent finibus magna congue lectus lacinia congue et id lacus. Suspendisse potenti. Ut tincidunt aliquet ipsum id vehicula.",
			"Phasellus lacinia, ante ac aliquam venenatis, velit mi bibendum diam, sit amet fringilla quam magna ut orci. Etiam non pretium ipsum. In posuere ligula efficitur nibh fermentum, a congue elit porta. Praesent scelerisque nulla sapien, vulputate malesuada augue gravida sit amet. In lacus neque, hendrerit tincidunt porttitor ut, blandit vitae risus. Curabitur vehicula tempor fermentum. Curabitur interdum ante rhoncus urna suscipit, id mollis quam viverra. Aenean sodales rhoncus nibh, nec finibus urna vehicula at. Ut imperdiet felis id sapien aliquet, sit amet lobortis elit sodales. Sed cursus maximus justo a pellentesque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris diam nunc, blandit eu pharetra posuere, ultrices id dolor. Pellentesque faucibus varius metus, vitae porttitor orci hendrerit eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget nunc est. Mauris odio risus, volutpat sit amet eros sit amet, feugiat maximus nisl.",
			"Duis blandit ipsum a ipsum vulputate tempus vitae quis urna. Nulla ac ultricies magna. Curabitur ultricies rhoncus tellus, vel imperdiet tellus semper id. Integer quis massa arcu. Praesent nisi velit, egestas nec magna ac, tincidunt volutpat nisi. Aliquam suscipit leo sed posuere vestibulum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut at volutpat mi, at bibendum elit. Donec non luctus velit. Nam convallis sagittis urna, nec venenatis ligula pellentesque eget. Pellentesque et nulla nisi. Quisque eros lectus, bibendum at pellentesque vel, pharetra non orci. Fusce sit amet laoreet justo. Etiam neque lacus, accumsan accumsan luctus ac, scelerisque et sem. Duis a libero eget velit volutpat maximus. Suspendisse in eros metus."
		]

	def __iter__(self):
		return self

	def __next__(self):
		if self.n < 10:
			result = self.data[self.n]
			self.n += 1
			return result
		else:
			raise StopIteration

