# Generated by Django 4.1.3 on 2022-11-15 03:39

from django.db import migrations, models
from django.contrib.auth.hashers import make_password

class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_initial_data'),
    ]

    # add the password field to the users model, making the hashed password
    # "password" as the default, this should only apply to the 10 built in users
    operations = [
        migrations.AddField("User", "password", models.CharField(max_length=100, default=make_password("password"))),
    ]