# Generated by Django 4.1.3 on 2022-11-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    # adding the verbose name to the password, and making the usernames unique
    dependencies = [
        ('products', '0004_user_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, verbose_name="The user's password"),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='What the user uses to login'),
        ),
    ]
